dist: bionic
language: r
pandoc_version: 2.1.1
sudo: false
cache: packages
r:
  - oldrel
  - release
script:
  - Rscript -e "xfun::in_dir('training', bookdown::render_book('index.Rmd', 'bookdown::gitbook'))"
  - Rscript -e "xfun::in_dir('reference', bookdown::render_book('index.Rmd', 'bookdown::gitbook'))"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN #set in travis-ci dashboard
  on:
    branch: main
  local_dir: docs
addons:
  apt:
#    sources:
#      - sourceline: 'ppa:opencpu/jq'
    packages:
      - librdf0-dev
      - libudunits2-dev
      - libnetcdf-dev
      - r-cran-ncdf4
      - libjq-dev
      - libv8-dev
